In [ ]:
import cupy as cp
import time
start_gpu = cp.cuda.Event()
end_gpu = cp.cuda.Event()

start_gpu.record()
start_cpu = time.perf_counter()
out = my_func(a)
end_cpu = time.perf_counter()
end_gpu.record()
end_gpu.synchronize()
t_gpu = cp.cuda.get_elapsed_time(start_gpu, end_gpu)
t_cpu = end_cpu - start_cpu

In [2]:
import numpy as np
import cupy as cp

In [4]:
np.array([-1], dtype=np.float32).astype(np.uint32)

array([4294967295], dtype=uint32)

In [5]:
cp.array([-1], dtype=np.float32).astype(np.uint32)

array([0], dtype=uint32)

In [6]:
np.array([float('inf')], dtype=np.float32).astype(np.int32)

/tmp/ipykernel_166766/2492872381.py:1: RuntimeWarning: invalid value encountered in cast
  np.array([float('inf')], dtype=np.float32).astype(np.int32)


array([-2147483648], dtype=int32)

In [7]:
cp.array([float('inf')], dtype=np.float32).astype(np.int32)

array([2147483647], dtype=int32)

In [13]:
x = np.array([0, 1, 2])
x[2]

2

In [17]:
x = cp.array([0, 1, 2])
x[[1, 3]] = 10
x

array([10, 10,  2])

In [18]:
print(type(np.sum(np.arange(3))))
print(type(cp.sum(cp.arange(3))))

<class 'numpy.int64'>
<class 'cupy.ndarray'>
